<?php
echo "<h6>Admin Panel</h6><ul class='alt'>";
echo "<li><a href='".$this->baseUrl('/admin/index')."'>New Post</a></li>";
echo "<li><a href='".$this->baseUrl('/admin/editpost/view/post')."'>Edit Posts</a></li>";
echo "<li><a href='".$this->baseUrl('/admin/editcomment/view/unread')."'>Edit Comments</a></li>";
echo "<li><a href='".$this->baseUrl('/admin/editrecipe')."'>Edit Recipes</a></li>";
echo "<li><a href='".$this->baseUrl('/admin/editrecipeuser')."'>Edit Recipe Users</a></li>";
echo "<li><a href='".$this->baseUrl('/admin/managefiles/view/filename')."'>Manage Files</a></li>";
echo "<li><a href='".$this->baseUrl('/admin/logs')."'>View Logs</a></li>";
echo "<li><a href='".$this->baseUrl('/admin/options')."'>Site Options</a></li>";
echo "<li><a href='".$this->baseUrl('/admin/account')."'>Admin Options</a></li>";
echo "<li><a href='".$this->baseUrl('/admin/users/view/user')."'>User Options</a></li>";
echo "</ul>";