<div class="clear"></div>

<div id="footer">
	&copy; Copyright 2010&ndash;<?php echo date('Y'); ?> <a style="text-decoration:none; color:#999;" rel="nofollow" href="<?php echo $this->baseUrl('/admin/'); ?>">Michael Yagi</a>
	<br>
	<a href="http://www.facebook.com/michael.t.yagi"><span class="icon social small darkgray" data-icon="F"></span></a>
	<a href="https://plus.google.com/114642071629999257411"><span class="icon social small darkgray" data-icon="G"></span></a>	
	<a href="http://ca.linkedin.com/pub/michael-yagi/35/428/252"><span class="icon social small darkgray" data-icon="I"></span></a>
	<a href="http://soundcloud.com/secondfiddle"><span class="icon social medium darkgray" data-icon="m"></span></a>
	<a href="mailto:michaeltyagi@gmail.com"><span class="icon medium darkgray" data-icon="@"></span></a>
	<a href="<?php echo $this->baseUrl('/feed'); ?>"><span class="icon social small darkgray" data-icon="r"></span></a>
	<a id="link-top" href="#top-of-page">Top</a>
</div>