<script type="text/javascript" language="JavaScript">
	$(function() {
		$('#frontpagecarousel').carousel({
			'pause',
			interval: 2000
		})
	});
</script>

<!-- Description -->
<div class="row">
	<div class="span12">
		<div class="page-header">
 			<h1>Short description of what we do...</h1>
 			<p><a href="#">Learn more...</a></p>
		</div>
	</div>
</div>

<!-- Carousel -->
<div class="row">
	<div class="span8">
		<div id="frontpagecarousel" class="carousel">
			<div class="carousel-inner">
   				<div class="item active">
   	 				<a href="#1"><img src="http://twitter.github.com/bootstrap/assets/img/bootstrap-mdo-sfmoma-01.jpg" alt="image 1"></a>
   					<div class="carousel-caption">
   	   	    			<h4>First Thumbnail label</h4>
   	   	    	  		<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
	   	   			</div>
    			</div>
    			<div class="item">
    				<a href="#2"><img src="http://twitter.github.com/bootstrap/assets/img/bootstrap-mdo-sfmoma-02.jpg" alt="image 2"></a>
	    			<div class="carousel-caption">
    	   	   	 	    <h4>Second Thumbnail label</h4>
        		   	 	<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
           	 		</div>
	    		</div>
    		<div class="item">
    				<a href="#3"><img src="http://twitter.github.com/bootstrap/assets/img/bootstrap-mdo-sfmoma-03.jpg" alt="image 3"></a>
    				<div class="carousel-caption">
	       	        	<h4>Third Thumbnail label</h4>
    	   	 	    	<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        		  	</div>
	   			</div>
 			</div>
	  		<!-- Carousel nav -->
  			<a class="carousel-control left" href="#frontpagecarousel" data-slide="prev">&lsaquo;</a>
	  		<a class="carousel-control right" href="#frontpagecarousel" data-slide="next">&rsaquo;</a>
		</div>
	</div>
	<div class="span4">
		<a href="#"><img src="http://placehold.it/360x220" alt=""></a>
		<a href="#"><img src="http://placehold.it/360x220" alt=""></a>
	</div>
</div>

<!-- Top List -->
<div class="row">
	<div class="span8">
		<h2>Top N</h2>
		<table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>Track Title</th>
            <th>Release Date</th>
            <th>More Info</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>1</td>
            <td>Mark</td>
            <td>Otto</td>
            <td>CSS</td>
          </tr>
          <tr>
            <td>2</td>
            <td>Jacob</td>
            <td>Thornton</td>
            <td>Javascript</td>
          </tr>
          <tr>
            <td>3</td>
            <td>Stu</td>
            <td>Dent</td>
            <td>HTML</td>
          </tr>
        </tbody>
      </table>
	</div>
	
	<div class="span4">
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eu accumsan urna. Curabitur non libero eget nibh ullamcorper malesuada a ut erat. Aliquam erat volutpat. Integer auctor, odio ac iaculis viverra, nibh quam imperdiet nisi, id accumsan felis risus hendrerit mi. Aenean dignissim lacus non ante tincidunt ultrices. Fusce euismod hendrerit orci eget gravida. Morbi non orci libero, tincidunt volutpat sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis eget justo eget tellus pulvinar tempor. Pellentesque ligula lorem, blandit quis sodales sit amet, tristique a metus. Vestibulum sit amet sapien sem, a congue diam.</p>
		<p>Aliquam sit amet eros at nisi viverra aliquet. Aenean dictum imperdiet felis sed suscipit. Quisque bibendum lacus at velit malesuada gravida. Nunc faucibus mi sit amet eros adipiscing facilisis. Nam molestie suscipit velit, vel ultrices mi facilisis at. Phasellus metus orci, lacinia laoreet porta sit amet, malesuada et enim. Quisque placerat elit quis dui cursus non mollis diam cursus. Aliquam sagittis mi sed est porttitor vel luctus diam vestibulum. Suspendisse id elit ante. Suspendisse blandit lobortis feugiat. In dignissim imperdiet consectetur. Aenean aliquam cursus vestibulum. Nulla tincidunt tellus id magna rhoncus quis mollis turpis volutpat. Mauris nec nulla quis lorem fermentum lacinia quis sit amet ipsum. Donec consectetur dui vel lectus volutpat rhoncus.</p>
	</div>
</div>