<div id="footer-top">
	<div class="container">
		<div class="row">
			<div class="span4">
				<h4>About Us</h4>
				<ul class="unstyled">
    				<li><a href="#">Item 1</a></li>
    				<li><a href="#">Item 2</a></li>
    				<li><a href="#">Item 3</a></li>
	    			<li><a href="#">Item 4</a></li>
    				<li><a href="#">Item 5</a></li>
  				</ul>
			</div>
	
			<div class="span4">
				<h4>Follow Us</h4>
				<ul class="unstyled">
    				<li><a href="#">Item 1</a></li>
	    			<li><a href="#">Item 2</a></li>
		    		<li><a href="#">Item 3</a></li>
    				<li><a href="#">Item 4</a></li>
    				<li><a href="#">Item 5</a></li>
		  		</ul>	
			</div>
	
			<div class="span4">
				<h4>Partners</h4>
				<ul class="unstyled">
    				<li><a href="#">Item 1</a></li>
	    			<li><a href="#">Item 2</a></li>
			    	<li><a href="#">Item 3</a></li>
    				<li><a href="#">Item 4</a></li>
    				<li><a href="#">Item 5</a></li>
		  		</ul>	
			</div>
		</div>
	</div>
</div>

<div id="footer-bottom">
	<div class="container">
		<div class="row">
			<div class="span12">
				<p>&copy; Company Name</p>
			</div>
		</div>
	</div>
</div>