<?php
$media = $this->media;
?>

<h3>Carleton University Chamber Music Concert 2012</h3>

<iframe width="420" height="315" src="http://www.youtube.com/embed/rcgzljrRJto" frameborder="0" allowfullscreen></iframe>
<div id='CommentForm'>
<p>
Chausson Concerto for Violin, Piano and String Quartet, II. Sicilienne<br><br>
Emil Azuma Prikryl - piano<br>
Michael Yagi - violin<br>
Reiko Lokker - violin<br>
Kelly Tang - violin<br>
Changsen Wang - viola<br>
Agnes Malkinson - cello
</p>
</div>