<script type="text/javascript" language="javascript">
	
	function deletechecked(message)
	{
		var answer = confirm("Delete post '" + message + "'?")
		if (answer)
    	{
        	document.messages.submit();
    	}
    
    	return false; 
	}

</script>

<?php
$objpage = $this->objpager;
$paginator = $this->paginator;

echo "<h3 style='display:inline;'>Welcome ".$this->user."</h3>&nbsp;&nbsp;<a style='float:right;' class='button' href='".$this->baseUrl('admin/logout')."'>Sign out</a>";
echo "<p style='margin-top:0px; margin-bottom:25px;'>".$this->expiretime."</p>";
echo "<h4>Edit Posts</h4>";

if ($this->err==1)
{
	echo "<div class='notice error'><span class='icon medium' data-icon='X'></span>Choose an action <a href='#close' class='icon close' data-icon='x'></a></div>";
}
else if ($this->err==2)
{
	echo "<div class='notice error'><span class='icon medium' data-icon='X'></span>An unknown error occurred <a href='#close' class='icon close' data-icon='x'></a></div>";
}
else if ($this->err==3)
{
	echo "<div class='notice error'><span class='icon medium' data-icon='X'></span>No posts chosen <a href='#close' class='icon close' data-icon='x'></a></div>";
}
else if($this->msg==1)
{
	echo "<div class='notice success'><span class='icon medium' data-icon='C'></span>Successful Edit <a href='#close' class='icon close' data-icon='x'></a></div>";
}
else if($this->msg==2)
{
	echo "<div class='notice success'><span class='icon medium' data-icon='C'>C</span>Nothing has changed <a href='#close' class='icon close' data-icon='x'></a></div>";
}

$sortby = Zend_Controller_Front::getInstance()->getRequest()->getParam('view');
$getSort = '';
if ($sortby == "post")
{
	$getSort = 'view/post';
	echo "Sort by: <a href='".$this->baseUrl('admin/editpost/view/status/')."'>Status</a> | Post<br>";
}
else if ($sortby == "status")
{
	$getSort = 'view/status';
	echo "Sort by: Status | <a href='".$this->baseUrl('admin/editpost/view/post/')."'>Post</a><br>";
}
else
{
	echo "Sort by: <a href='".$this->baseUrl('admin/editpost/view/status/')."'>Status</a> | <a href='".$this->baseUrl('admin/editpost/view/post/')."'>Post</a><br>";
}

echo $paginator;
echo "<br><br>"; 
echo "<div id='WrapperBox'>";
?>
	<form name="active" action="/admin/editpost" method="post">
	<select name="action" class="fancy">
		<option value="choose">-- Choose Action --</option>
		<option value="1">Activate</option>
		<option value="0">Deactivate</option>
		<option value="2">Delete</option>
	</select>
	<input style="padding: 5px 6px 5px 2px;" type="submit" name="submit" value="Go" />

	<table style="margin-top:-10px;" cellspacing="0" cellpadding="0">
	<br><br>
	<thead><tr>
		<th>Action</th>
		<th>Title</th>
		<th>Status</th>
	</tr></thead>
	<tbody>
	
		<?php 
		foreach($objpage->getCurrentItems() as $value)
		{
			echo "<tr><td><input type='checkbox' name='postaction[]' value='".$value['id']."' /></td>";
			$title = $value['title'];
			if (strlen($value['title']) >= 60)
			{
				$title = substr($value['title'], 0, 60)."...";
			}
			echo "<td>".$title."</td>";
			if ($value['isActive'])
			{
				echo "<td><a href='".$this->baseUrl('admin/editarticle/id/'.$value['id'])."' title='Edit Post'><span class='icon small darkgray' data-icon='7'></span></a> <span class='icon small green' data-icon='C' title='Active'></span>"; //"<a onclick='return deletechecked(\"".$title."\");' href='".$this->baseUrl('admin/editpost/'.$getSort.'/postaction/delete/id/'.$value['id'])."' title='Delete Post'><span class='icon small red' data-icon='m'></span></a></td>";
			}
			else
			{
				echo "<td><a href='".$this->baseUrl('admin/editarticle/id/'.$value['id'])."' title='Edit Post'><span class='icon small darkgray' data-icon='7'></span></a> <span class='icon small red' data-icon='x' title='Inactive'></span>"; //"<a onclick='return deletechecked(\"".$title."\");' href='".$this->baseUrl('admin/editpost/'.$getSort.'/postaction/delete/id/'.$value['id'])."' title='Delete Post'><span class='icon small red' data-icon='m'></span></a></td>";
			}
			echo "</tr>";
		}
		?>
	</tbody>
	</table>
	<?php
	if (isset($_GET['page'])&&isset($_GET['count']))
	{
	?>
	<input type="hidden" name="page" value="<?php echo $_GET['page']; ?>">
	<input type="hidden" name="count" value="<?php echo $_GET['count']; ?>">
	<?php
	}
	$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('view');
	if (isset($param))
	{
	?>
	<input type="hidden" name="view" value="<?php echo $param; ?>">
	<?php
	}
	?>
	</form>
</div>
<br><?php echo $paginator; ?>