<?php
echo "<h3 style='display:inline;'>Welcome ".$this->user."</h3>&nbsp;&nbsp;<a style='float:right;' class='button' href='".$this->baseUrl('admin/logout')."'>Sign out</a>";
echo "<p style='margin-top:0px; margin-bottom:25px;'>".$this->expiretime."</p>";
echo "<h4>Edit Post</h4>";

$article = $this->article;

echo "<div id='CommentForm' class='CommentForm_new'>";
if($this->msg==1)
{
	echo "<div class='notice success'><span class='icon medium' data-icon='C'></span>Successful Edit <a href='#close' class='icon close' data-icon='x'></a></div>";
}
else if($this->msg==2)
{
	echo "<div class='notice success'><span class='icon medium' data-icon='C'></span>Successfully Added <a href='#close' class='icon close' data-icon='x'></a></div>";
}
else if($this->err==1)
{
	echo "<div class='notice error'><span class='icon medium' data-icon='X'></span>Error in editing <a href='#close' class='icon close' data-icon='x'></a></div>";
}
else if($this->err==2)
{
	echo "<div class='notice error'><span class='icon medium' data-icon='X'></span>Invalid Form <a href='#close' class='icon close' data-icon='x'></a></div>";
}
	
if(isset($this->postid) && $this->postid > 0)
{
	echo "<a href='".$this->baseUrl('news/article/id/'.$this->postid)."'>View Post</a>";
}
echo $this->editpostform;
echo "</div>";