<script type="text/javascript" language="javascript">
	
	function deletechecked(message)
	{
		var answer = confirm("Delete post '" + message + "'?")
		if (answer)
    	{
        	document.messages.submit();
    	}
    
    	return false; 
	}

	$(document).ready(function()
	{
		$('.action_checkbox').prepend('<input id="check_all" type="checkbox" />&nbsp;');
	
    	$('#check_all').click(function()
    	{
    		if ($('#comment-table .comment-row').attr('checked'))
    		{
    			$('#comment-table .comment-row').attr('checked', false);
       		}
       		else
       		{
       			$('#comment-table .comment-row').attr('checked', 'checked');
       		}
    	});
	});
	
</script>

<?php
$objpage = $this->objpager;
$paginator = $this->paginator;

echo "<h3 style='display:inline;'>Welcome ".$this->user."</h3>&nbsp;&nbsp;<a style='float:right;' class='button' href='".$this->baseUrl('admin/logout')."'>Sign out</a>";
echo "<p style='margin-top:0px; margin-bottom:25px;'>".$this->expiretime."</p>";
echo "<h4>Edit Comments</h4>";

if ($this->err==1)
{
	echo "<div class='notice error'><span class='icon medium' data-icon='X'></span>Choose an action <a href='#close' class='icon close' data-icon='x'></a></div>";
}
else if ($this->err==2)
{
	echo "<div class='notice error'><span class='icon medium' data-icon='X'></span>An unknown error occurred <a href='#close' class='icon close' data-icon='x'></a></div>";
}
else if ($this->err==3)
{
	echo "<div class='notice error'><span class='icon medium' data-icon='X'></span>No comments chosen <a href='#close' class='icon close' data-icon='x'></a></div>";
}
else if($this->msg==1)
{
	echo "<div class='notice success'><span class='icon medium' data-icon='C'></span>Successful Edit <a href='#close' class='icon close' data-icon='x'></a></div>";
}
else if($this->msg==2)
{
	echo "<div class='notice success'><span class='icon medium' data-icon='C'>C</span>Nothing has changed <a href='#close' class='icon close' data-icon='x'></a></div>";
}     

$sortby = Zend_Controller_Front::getInstance()->getRequest()->getParam('view');
$getSort = '';
if ($sortby == "post")
{
	$getSort = 'view/post';
	echo "Sort by: <a href='".$this->baseUrl('admin/editcomment/view/unread/')."'>Unread</a> | <a href='".$this->baseUrl('admin/editcomment/view/status/')."'>Status</a> | Post | <a href='".$this->baseUrl('admin/editcomment/view/articleid/')."'>By Article Post</a><br>";
}
else if ($sortby == "status")
{
	$getSort = 'view/status';
	echo "Sort by: <a href='".$this->baseUrl('admin/editcomment/view/unread/')."'>Unread</a> | Status | <a href='".$this->baseUrl('admin/editcomment/view/post/')."'>Post</a> | <a href='".$this->baseUrl('admin/editcomment/view/articleid/')."'>By Article Post</a><br>";
}
else if ($sortby == "articleid")
{
	$getSort = 'view/articleid';
	echo "Sort by: <a href='".$this->baseUrl('admin/editcomment/view/unread/')."'>Unread</a> | <a href='".$this->baseUrl('admin/editcomment/view/status/')."'>Status</a> | <a href='".$this->baseUrl('admin/editcomment/view/post/')."'>Post</a> | By Article Post<br>";
}
else if ($sortby == "unread")
{
	$getSort = 'view/unread';
	echo "Sort by: Unread | <a href='".$this->baseUrl('admin/editcomment/view/status/')."'>Status</a> | <a href='".$this->baseUrl('admin/editcomment/view/post/')."'>Post</a> | <a href='".$this->baseUrl('admin/editcomment/view/articleid/')."'>By Article Post</a><br>";	
}
else
{
	echo "Sort by: <a href='".$this->baseUrl('admin/editcomment/view/unread/')."'>Unread</a> | <a href='".$this->baseUrl('admin/editcomment/view/status/')."'>Status</a> | <a href='".$this->baseUrl('admin/editcomment/view/post/')."'>Post</a> | <a href='".$this->baseUrl('admin/editcomment/view/articleid/')."'>By Article Post</a><br>";
}

echo $paginator;
echo "<br><br>"; 
echo "<div id='WrapperBox'>";
?>
	<form name="active" action="/admin/editcomment" method="post">
	<select name="action" class="fancy">
		<option value="choose">-- Choose Action --</option>
		<option value="1">Activate</option>
		<option value="0">Deactivate</option>
		<option value="3">Mark as Read</option>
		<option value="4">Mark as Unread</option>
		<option value="2">Delete</option>
	</select>
	<input style="padding: 5px 6px 5px 2px;" type="submit" name="submit" value="Go" />

	<table id="comment-table" style="margin-top:-10px;" cellspacing="0" cellpadding="0">
	<br><br>
	<thead>
		<tr>
			<th class="action_checkbox" style="width:60px;">Action</th>
			<th style="width:45px;">Post ID</th>
			<th style="width:450px;">Comment</th>
			<th>Status</th>
		</tr>
	</thead>
	<tbody>
	
		<?php 
		foreach($objpage->getCurrentItems() as $value)
		{
			echo "<tr><td><input type='checkbox' name='postaction[]' class='comment-row' value='".$value['id']."' /></td>";
			echo "<td><a href='".$this->baseUrl('news/article/id/'.$value['blogid'])."'>".$value['blogid']."</a></td>";
			$comment = $value['comment'];
			if (strlen($value['comment']) >= 45)
			{
				$comment = substr($value['comment'], 0, 45)."...";
			}
			if($value['markedRead'])
			{
				echo "<td>".$comment."</td>";
			}
			else
			{
				echo "<td><strong>".$comment."<strong></td>";
			}
			if ($value['isActive'])
			{
				echo "<td><a href='".$this->baseUrl('admin/editsinglecomment/id/'.$value['id'])."'><span class='icon small darkgray' data-icon='7' title='Edit Comment'></span></a> <span class='icon small green' data-icon='C' title='Active'></span>"; 
			}
			else
			{
				echo "<td><a href='".$this->baseUrl('admin/editsinglecomment/id/'.$value['id'])."'><span class='icon small darkgray' data-icon='7' title='Edit Comment'></span></a> <span class='icon small red' data-icon='x' title='Inactive'></span>"; 
			}
			echo "</tr>";
		}
		?>
	</tbody>
	</table>
	<?php
	if (isset($_GET['page'])&&isset($_GET['count']))
	{
	?>
	<input type="hidden" name="page" value="<?php echo $_GET['page']; ?>">
	<input type="hidden" name="count" value="<?php echo $_GET['count']; ?>">
	<?php
	}
	$param = Zend_Controller_Front::getInstance()->getRequest()->getParam('view');
	if (isset($param))
	{
	?>
	<input type="hidden" name="view" value="<?php echo $param; ?>">
	<?php
	}
	?>
	</form>
</div>
<br><?php echo $paginator; ?>