<?php
echo "<h4>Admin Login</h4>";
if ($this->err == 1)
{
	echo "<div class='notice error'><span class='icon medium' data-icon='X'></span>Incorrect username or password <a href='#close' class='icon close' data-icon='x'></a></div>";
}
else if ($this->err == 2)
{
	echo "<div class='notice error'><span class='icon medium' data-icon='X'></span>Error in submission <a href='#close' class='icon close' data-icon='x'></a></div>";
}

echo "<div id='CommentForm' class='CommentForm_new'>";
echo $this->loginform;
echo "</div>";