<?php
$user = $this->user;

echo "<h4>Add Recipe</h4>";
if ($this->err == 1) {
	echo "<div class='notice error'><span class='icon medium' data-icon='X'></span>Error in form<a href='#close' class='icon close' data-icon='x'></a></div>";
} else if ($this->err == 2) {
	echo "<div class='notice error'><span class='icon medium' data-icon='X'></span>Error in submission <a href='#close' class='icon close' data-icon='x'></a></div>";
}

echo "<div id='CommentForm' class='CommentForm_new'>";
echo $this->recipeform;
echo "</div>";


echo '<script type="text/javascript">';

//Dynamic tag creation using tag-it
echo '$("#recipeTags").append("<li>dummy</li>");';
echo '$("#recipeTags").empty();';

echo '</script>';